let player = {};

const defaultPlayer = {
	gold: new Decimal(10),

	firstCost: new Decimal(10),
	secondCost: new Decimal(1000),
	thirdCost: new Decimal(1e9),
	fourthCost: new Decimal(1e16),
	fifthCost: new Decimal(1e25),
	sixthCost: new Decimal(1e36),
	seventhCost: new Decimal(1e49),
	eighthCost: new Decimal(1e64),

	firstCostAfterInf: new Decimal('1e309'),
	secondCostAfterInf: new Decimal('1e311'),
	thirdCostAfterInf: new Decimal('1e315'),
	fourthCostAfterInf: new Decimal('1e324'),
	fifthCostAfterInf: new Decimal('1e330'),
	sixthCostAfterInf: new Decimal('1e342'),
	seventhCostAfterInf: new Decimal('1e357'),
	eighthCostAfterInf: new Decimal('1e368'),

	firstNewBaseCost: new Decimal(1e25),
	secondNewBaseCost: new Decimal(1e37),
	thirdNewBaseCost: new Decimal(1e50),
	fourthNewBaseCost: new Decimal(1e62),
	fifthNewBaseCost: new Decimal(1e75),
	sixthNewBaseCost: new Decimal(1e87),
	seventhNewBaseCost: new Decimal(1e100),
	eighthNewBaseCost: new Decimal(1e112),

	firstNewBaseCostInc: new Decimal(2),
	secondNewBaseCostInc: new Decimal(4),
	thirdNewBaseCostInc: new Decimal(8),
	fourthNewBaseCostInc: new Decimal(16),
	fifthNewBaseCostInc: new Decimal(32),
	sixthNewBaseCostInc: new Decimal(64),
	seventhNewBaseCostInc: new Decimal(128),
	eighthNewBaseCostInc: new Decimal(256),

	firstAmount: new Decimal(0),
	secondAmount: new Decimal(0),
	thirdAmount: new Decimal(0),
	fourthAmount: new Decimal(0),
	fifthAmount: new Decimal(0),
	sixthAmount: new Decimal(0),
	seventhAmount: new Decimal(0),
	eighthAmount: new Decimal(0),

	firstBought: new Decimal(0),
	secondBought: new Decimal(0),
	thirdBought: new Decimal(0),
	fourthBought: new Decimal(0),
	fifthBought: new Decimal(0),
	sixthBought: new Decimal(0),
	seventhBought: new Decimal(0),
	eighthBought: new Decimal(0),

	firstMult: new Decimal(8),
	secondMult: new Decimal(4),
	thirdMult: new Decimal(1),
	fourthMult: new Decimal(1),
	fifthMult: new Decimal(1),
	sixthMult: new Decimal(1),
	seventhMult: new Decimal(1),
	eighthMult: new Decimal(1),

	firstFinalMult: new Decimal(1),
	secondFinalMult: new Decimal(1),
	thirdFinalMult: new Decimal(1),
	fourthFinalMult: new Decimal(1),
	fifthFinalMult: new Decimal(1),
	sixthFinalMult: new Decimal(1),
	seventhFinalMult: new Decimal(1),
	eighthFinalMult: new Decimal(1),

	firstPrestige: new Decimal(0),
	secondPrestige: new Decimal(0),
	thirdPrestige: new Decimal(0),
	fourthPrestige: new Decimal(0),
	fifthPrestige: new Decimal(0),
	sixthPrestige: new Decimal(0),
	seventhPrestige: new Decimal(0),
	eighthPrestige: new Decimal(0),

	firstPrestigeCost: new Decimal(3),
	secondPrestigeCost: new Decimal(5),
	thirdPrestigeCost: new Decimal(7),
	fourthPrestigeCost: new Decimal(9),
	fifthPrestigeCost: new Decimal(11),
	sixthPrestigeCost: new Decimal(13),
	seventhPrestigeCost: new Decimal(15),
	eighthPrestigeCost: new Decimal(17),

	firstNewPrestigeCost: new Decimal(4),
	secondNewPrestigeCost: new Decimal(8),
	thirdNewPrestigeCost: new Decimal(12),
	fourthNewPrestigeCost: new Decimal(16),
	fifthNewPrestigeCost: new Decimal(20),
	sixthNewPrestigeCost: new Decimal(24),
	seventhNewPrestigeCost: new Decimal(28),
	eighthNewPrestigeCost: new Decimal(32),

	milliseconds: new Decimal(0),
	seconds: new Decimal(0),
	minuts: new Decimal(0),
	hours: new Decimal(0),
	days: new Decimal(0),
	years: new Decimal(0),
	totalSeconds: new Decimal(0),
	secondsInExpansion: new Decimal(0),
	secondsInOmega: new Decimal(0),
	secondsInReality: new Decimal(0),

	allMult: new Decimal(1),
	allMultFinal: new Decimal(1),
	allMultCost: new Decimal(1000),
	allMultFinalCost: new Decimal(1000),
	allMultCostInc: new Decimal(1000),
	allMultGain: new Decimal(1.05),
	allMultGainFinal: new Decimal(1),
	allMultFromPrestige: new Decimal(1),
	allMultBought: new Decimal(0),
	allMultFromFirstExpansionUpgrade: new Decimal(1),
	allMultGainFromSecondExpansionUpgrade: new Decimal(1),
	allMultGainFromTwelfthExpansionUpgrade: new Decimal(1),
	allMultGainFromSecondGammaUpgrade: new Decimal(1),
	allMultFromFourthExpansionUpgrade: new Decimal(1),
	allMultFromEighthExpansionUpgrade: new Decimal(1),
	allMultFromTenthExpansionUpgrade: new Decimal(1),
	allMultFromTenthExpansionUpgrade2x4y: new Decimal(1),
	allMultFromFirstGammaUpgrade: new Decimal(1),
	allMultFromFifthGammaUpgrade: new Decimal(1),
	allMultNewBaseCost: new Decimal(1e52),
	allMultNewBaseCostInc: new Decimal(100),

	multPerBuy: new Decimal(1.6),
	multPerBuyFinal: new Decimal(1.6),
	multPerBuyFromOmegaUpgrade1x1y: new Decimal(1),

	maxPrestige: new Decimal(15),
	prestigeEffectFromThirdGammaUpgrade: new Decimal(1),
	prestigeEffectFromOmegaUpgrade2x1y: new Decimal(1),

	hasUnlockedExpansion: false,
	expansionPoints: new Decimal(0),
	expansionPointMult: new Decimal(1),
	expansionPointMultBought: new Decimal(0),
	expansionPointMultFinal: new Decimal(1),
	expansionPointMultCost: new Decimal(10),
	expansionPointMultCostInc: new Decimal(10),
	expansionPointMultCostIncInc: new Decimal(2),
	expansions: new Decimal(0),
	expansionCost: new Decimal('1e308'),
	expansionPointMultFromNinthExpansionUpgrade: new Decimal(1),
	expansionPointMultFromThirteenthExpansionUpgrade: new Decimal(1),
	expansionPointMultFromFirstAlphaUpgrade: new Decimal(1),
	expansionPointMultFromFifthAlphaUpgrade: new Decimal(1),
	expansionUpgradeThirteenEffectIncrease: new Decimal(1),
	expansionPointMultFromSecondAlphaUpgrade: new Decimal(1),
	expansionPointMultFromOmegaUpgrade4x1y: new Decimal(1),

	electricity: new Decimal(0),
	electricityEffectFromThirdBetaUpgrade: new Decimal(1),

	firstExpansionGeneratorCost: new Decimal(1),
	secondExpansionGeneratorCost: new Decimal(100),
	thirdExpansionGeneratorCost: new Decimal(1e4),
	fourthExpansionGeneratorCost: new Decimal(1e6),
	fifthExpansionGeneratorCost: new Decimal(1e8),
	sixthExpansionGeneratorCost: new Decimal(1e10),
	seventhExpansionGeneratorCost: new Decimal(1e12),
	eighthExpansionGeneratorCost: new Decimal(1e14),

	firstExpansionGeneratorCostInc: new Decimal(3),
	secondExpansionGeneratorCostInc: new Decimal(6),
	thirdExpansionGeneratorCostInc: new Decimal(9),
	fourthExpansionGeneratorCostInc: new Decimal(12),
	fifthExpansionGeneratorCostInc: new Decimal(15),
	sixthExpansionGeneratorCostInc: new Decimal(18),
	seventhExpansionGeneratorCostInc: new Decimal(21),
	eighthExpansionGeneratorCostInc: new Decimal(24),

	firstExpansionGeneratorCostIncInc: new Decimal(1.5),
	secondExpansionGeneratorCostIncInc: new Decimal(2),
	thirdExpansionGeneratorCostIncInc: new Decimal(2.5),
	fourthExpansionGeneratorCostIncInc: new Decimal(3),
	fifthExpansionGeneratorCostIncInc: new Decimal(3.5),
	sixthExpansionGeneratorCostIncInc: new Decimal(4),
	seventhExpansionGeneratorCostIncInc: new Decimal(4.5),
	eighthExpansionGeneratorCostIncInc: new Decimal(5),

	firstExpansionGeneratorAmount: new Decimal(0),
	secondExpansionGeneratorAmount: new Decimal(0),
	thirdExpansionGeneratorAmount: new Decimal(0),
	fourthExpansionGeneratorAmount: new Decimal(0),
	fifthExpansionGeneratorAmount: new Decimal(0),
	sixthExpansionGeneratorAmount: new Decimal(0),
	seventhExpansionGeneratorAmount: new Decimal(0),
	eighthExpansionGeneratorAmount: new Decimal(0),

	firstExpansionGeneratorBought: new Decimal(0),
	secondExpansionGeneratorBought: new Decimal(0),
	thirdExpansionGeneratorBought: new Decimal(0),
	fourthExpansionGeneratorBought: new Decimal(0),
	fifthExpansionGeneratorBought: new Decimal(0),
	sixthExpansionGeneratorBought: new Decimal(0),
	seventhExpansionGeneratorBought: new Decimal(0),
	eighthExpansionGeneratorBought: new Decimal(0),

	firstExpansionGeneratorMult: new Decimal(1),
	secondExpansionGeneratorMult: new Decimal(1),
	thirdExpansionGeneratorMult: new Decimal(1),
	fourthExpansionGeneratorMult: new Decimal(1),
	fifthExpansionGeneratorMult: new Decimal(1),
	sixthExpansionGeneratorMult: new Decimal(1),
	seventhExpansionGeneratorMult: new Decimal(1),
	eighthExpansionGeneratorMult: new Decimal(1),

	firstExpansionGeneratorFinalMult: new Decimal(1),
	secondExpansionGeneratorFinalMult: new Decimal(1),
	thirdExpansionGeneratorFinalMult: new Decimal(1),
	fourthExpansionGeneratorFinalMult: new Decimal(1),
	fifthExpansionGeneratorFinalMult: new Decimal(1),
	sixthExpansionGeneratorFinalMult: new Decimal(1),
	seventhExpansionGeneratorFinalMult: new Decimal(1),
	eighthExpansionGeneratorFinalMult: new Decimal(1),

	expansionUpgrade1: false,
	expansionUpgrade2: false,
	expansionUpgrade3: false,
	expansionUpgrade4: false,
	expansionUpgrade5: false,
	expansionUpgrade6: false,
	expansionUpgrade7: false,
	expansionUpgrade8: false,
	expansionUpgrade9: false,
	expansionUpgrade10: false,
	expansionUpgrade11: false,
	expansionUpgrade12: false,
	expansionUpgrade13: false,
	expansionUpgrade14: false,
	expansionUpgrade15: false,

	firstExpansionMultFromUpgrades: new Decimal(1),
	expansionGeneratorAllMultFromEleventhExpansionUpgrade: new Decimal(1),
	expansionGeneratorAllMultFromFirstBetaUpgrade: new Decimal(1),
	firstExpansionGeneratorMultFromSecondBetaUpgrade: new Decimal(1),
	expansionGeneratorAllMultFromFifthBetaUpgrade: new Decimal(1),
	allExpansionGeneratorPow: new Decimal(1),

	hasUnlockedAutobuyers: false,
	prestigeAutobuyerChecked: false,
	generatorAutobuyerChecked: false,
	allMultAutobuyerChecked: false,
	expansionAutobuyerChecked: false,
	alphaBetaGammaAutobuyerChecked: false,
	expansionGeneratorAutobuyerChecked: false,
	expansionPointMultAutobuyerChecked: false,
	alphaBetaGammaUpgrade5AutobuyerChecked: false,
	simulationHeroAutobuyerChecked: false,
	fightingAutobuyerChecked: false,
	battleTowerAutobuyerChecked: false,
	build1AutobuyerChecked: false,
	build2AutobuyerChecked: false,
	build3AutobuyerChecked: false,
	build4AutobuyerChecked: false,
	omegaGeneratorAutobuyerChecked: false,
	electronUpgradesAutobuyerChecked: false,
	fillBarAutobuyerChecked: false,
	ascensionAutobuyerChecked: false,
	transcensionUpgradesAutobuyerChecked: false,
	hypercensionAutobuyerChecked: false,
	realityGeneratorAutobuyerChecked: false,

	alpha: new Decimal(0),
	alphaCost: new Decimal('1e2000'),
	alphaBought: new Decimal(0),
	alphaNewCost: new Decimal('1e500'),
	alphaNewCostInc: new Decimal(100),
	alphaUpgrade5FinalMult: new Decimal(1),
	alphaUpgrade5MultIncreaseFromOmegaUpgrade1x2y: new Decimal(1),
	beta: new Decimal(0),
	betaCost: new Decimal(1e8),
	betaBought: new Decimal(0),
	betaNewCost: new Decimal(100),
	betaNewCostInc: new Decimal(1.1),
	betaUpgrade5FinalMult: new Decimal(1),
	betaUpgrade5MultIncreaseFromOmegaUpgrade1x3y: new Decimal(1),
	betaUpgrade5MultIncreaseFromOmegaUpgrade4x3y: new Decimal(1),
	gamma: new Decimal(0),
	gammaCost: new Decimal(1e30),
	gammaBought: new Decimal(0),
	gammaNewCost: new Decimal(1e5),
	gammaNewCostInc: new Decimal(2),
	gammaUpgrade5FinalMult: new Decimal(1),
	gammaUpgrade5MultIncreaseFromOmegaUpgrade1x4y: new Decimal(1),
	hasUnlockedABG: false,

	alphaUpgrade1: new Decimal(0),
	alphaUpgrade2: new Decimal(0),
	alphaUpgrade3: new Decimal(0),
	alphaUpgrade4: new Decimal(0),
	alphaUpgrade5: new Decimal(0),

	betaUpgrade1: new Decimal(0),
	betaUpgrade2: new Decimal(0),
	betaUpgrade3: new Decimal(0),
	betaUpgrade4: new Decimal(0),
	betaUpgrade5: new Decimal(0),

	gammaUpgrade1: new Decimal(0),
	gammaUpgrade2: new Decimal(0),
	gammaUpgrade3: new Decimal(0),
	gammaUpgrade4: new Decimal(0),
	gammaUpgrade5: new Decimal(0),

	firstOmegaGeneratorCost: new Decimal(1),
	secondOmegaGeneratorCost: new Decimal(100),
	thirdOmegaGeneratorCost: new Decimal(1e4),
	fourthOmegaGeneratorCost: new Decimal(1e6),
	fifthOmegaGeneratorCost: new Decimal(1e8),
	sixthOmegaGeneratorCost: new Decimal(1e10),
	seventhOmegaGeneratorCost: new Decimal(1e12),
	eighthOmegaGeneratorCost: new Decimal(1e14),

	firstOmegaGeneratorCostInc: new Decimal(2),
	secondOmegaGeneratorCostInc: new Decimal(3),
	thirdOmegaGeneratorCostInc: new Decimal(4),
	fourthOmegaGeneratorCostInc: new Decimal(5),
	fifthOmegaGeneratorCostInc: new Decimal(6),
	sixthOmegaGeneratorCostInc: new Decimal(7),
	seventhOmegaGeneratorCostInc: new Decimal(8),
	eighthOmegaGeneratorCostInc: new Decimal(9),

	firstOmegaGeneratorCostIncInc: new Decimal(1.1),
	secondOmegaGeneratorCostIncInc: new Decimal(1.1),
	thirdOmegaGeneratorCostIncInc: new Decimal(1.1),
	fourthOmegaGeneratorCostIncInc: new Decimal(1.1),
	fifthOmegaGeneratorCostIncInc: new Decimal(1.1),
	sixthOmegaGeneratorCostIncInc: new Decimal(1.1),
	seventhOmegaGeneratorCostIncInc: new Decimal(1.1),
	eighthOmegaGeneratorCostIncInc: new Decimal(1.1),

	firstOmegaGeneratorAmount: new Decimal(0),
	secondOmegaGeneratorAmount: new Decimal(0),
	thirdOmegaGeneratorAmount: new Decimal(0),
	fourthOmegaGeneratorAmount: new Decimal(0),
	fifthOmegaGeneratorAmount: new Decimal(0),
	sixthOmegaGeneratorAmount: new Decimal(0),
	seventhOmegaGeneratorAmount: new Decimal(0),
	eighthOmegaGeneratorAmount: new Decimal(0),

	firstOmegaGeneratorBought: new Decimal(0),
	secondOmegaGeneratorBought: new Decimal(0),
	thirdOmegaGeneratorBought: new Decimal(0),
	fourthOmegaGeneratorBought: new Decimal(0),
	fifthOmegaGeneratorBought: new Decimal(0),
	sixthOmegaGeneratorBought: new Decimal(0),
	seventhOmegaGeneratorBought: new Decimal(0),
	eighthOmegaGeneratorBought: new Decimal(0),

	firstOmegaGeneratorMult: new Decimal(1),
	secondOmegaGeneratorMult: new Decimal(1),
	thirdOmegaGeneratorMult: new Decimal(1),
	fourthOmegaGeneratorMult: new Decimal(1),
	fifthOmegaGeneratorMult: new Decimal(1),
	sixthOmegaGeneratorMult: new Decimal(1),
	seventhOmegaGeneratorMult: new Decimal(1),
	eighthOmegaGeneratorMult: new Decimal(1),

	firstOmegaGeneratorFinalMult: new Decimal(1),
	secondOmegaGeneratorFinalMult: new Decimal(1),
	thirdOmegaGeneratorFinalMult: new Decimal(1),
	fourthOmegaGeneratorFinalMult: new Decimal(1),
	fifthOmegaGeneratorFinalMult: new Decimal(1),
	sixthOmegaGeneratorFinalMult: new Decimal(1),
	seventhOmegaGeneratorFinalMult: new Decimal(1),
	eighthOmegaGeneratorFinalMult: new Decimal(1),

	omegaPoints: new Decimal(0),
	hasUnlockedOmega: false,
	omegaPointMult: new Decimal(1),
	omegaPointMultCost: new Decimal(10),
	omegaPointMultBought: new Decimal(0),
	omegaPointMultFinal: new Decimal(1),
	omegaPointMultFrom2x2y: new Decimal(1),
	omegas: new Decimal(0),

	omega: new Decimal(0),
	omegaEffect: new Decimal(1),

	omegaUpgrade1x1y: false,
	omegaUpgrade2x1y: false,
	omegaUpgrade3x1y: false,
	omegaUpgrade4x1y: false,
	omegaUpgrade1x2y: false,
	omegaUpgrade2x2y: false,
	omegaUpgrade3x2y: false,
	omegaUpgrade4x2y: false,
	omegaUpgrade1x3y: false,
	omegaUpgrade2x3y: false,
	omegaUpgrade3x3y: false,
	omegaUpgrade4x3y: false,
	omegaUpgrade1x4y: false,
	omegaUpgrade2x4y: false,
	omegaUpgrade3x4y: false,
	omegaUpgrade4x4y: false,

	omegaUpgrade1x1yMax: new Decimal(1),
	omegaUpgrade2x1yMax: new Decimal(1),
	omegaUpgrade3x1yMax: new Decimal(1),
	omegaUpgrade4x1yMax: new Decimal(1),
	omegaUpgrade1x2yMax: new Decimal(1),
	omegaUpgrade2x2yMax: new Decimal(1),
	omegaUpgrade3x2yMax: new Decimal(1),
	omegaUpgrade4x2yMax: new Decimal(1),
	omegaUpgrade1x3yMax: new Decimal(1),
	omegaUpgrade2x3yMax: new Decimal(1),
	omegaUpgrade3x3yMax: new Decimal(1),
	omegaUpgrade4x3yMax: new Decimal(1),
	omegaUpgrade1x4yMax: new Decimal(1),
	omegaUpgrade2x4yMax: new Decimal(1),
	omegaUpgrade3x4yMax: new Decimal(1),
	omegaUpgrade4x4yMax: new Decimal(1),

	omegaUpgrade1x1yBought: new Decimal(0),
	omegaUpgrade2x1yBought: new Decimal(0),
	omegaUpgrade3x1yBought: new Decimal(0),
	omegaUpgrade4x1yBought: new Decimal(0),
	omegaUpgrade1x2yBought: new Decimal(0),
	omegaUpgrade2x2yBought: new Decimal(0),
	omegaUpgrade3x2yBought: new Decimal(0),
	omegaUpgrade4x2yBought: new Decimal(0),
	omegaUpgrade1x3yBought: new Decimal(0),
	omegaUpgrade2x3yBought: new Decimal(0),
	omegaUpgrade3x3yBought: new Decimal(0),
	omegaUpgrade4x3yBought: new Decimal(0),
	omegaUpgrade1x4yBought: new Decimal(0),
	omegaUpgrade2x4yBought: new Decimal(0),
	omegaUpgrade3x4yBought: new Decimal(0),
	omegaUpgrade4x4yBought: new Decimal(0),

	omegaUpgradeCost: new Decimal(1),

	omegaUpgradeReset: false,

	simGold: new Decimal(0),
	stage: new Decimal(1),
	DPS: new Decimal(1),
	finalDPS: new Decimal(1),
	stageExponent: new Decimal(2),
	finalGPS: new Decimal(1),

	inGoldMode: false,
	inFightingMode: false,

	goldFarmerLevel: new Decimal(1),
	goldFarmerMult: new Decimal(1),
	goldFarmerCost: new Decimal(10),
	goldFarmerScale: new Decimal(1),
	goldFarmerScaleScale: new Decimal(1),
	goldFarmerScaleScaleScale: new Decimal(1),

	hybridLevel: new Decimal(1),
	hybridMult: new Decimal(1),
	hybridCost: new Decimal(10),
	hybridScale: new Decimal(1),
	hybridScaleScale: new Decimal(1),
	hybridScaleScaleScale: new Decimal(1),

	PVPLegendLevel: new Decimal(1),
	PVPLegendMult: new Decimal(1),
	PVPLegendCost: new Decimal(10),
	PVPLegendScale: new Decimal(1),
	PVPLegendScaleScale: new Decimal(1),
	PVPLegendScaleScaleScale: new Decimal(1),

	monsterTotalHP: new Decimal(10),
	monsterCurrentHP: new Decimal(10),

	resimulateDPSMult: new Decimal(1),
	resimulateStageExponentMult: new Decimal(1),

	firstSimUpgrade: new Decimal(1),
	firstSimUpgradeBought: false,

	secondSimUpgrade: new Decimal(1),
	secondSimUpgradeBought: false,

	thirdSimUpgrade: new Decimal(1),
	thirdSimUpgradeBought: false,

	fourthSimUpgrade: new Decimal(1),
	fourthSimUpgradeBought: false,
	fourthSimUpgradeTotalLevels: new Decimal(30),

	fifthSimUpgrade: new Decimal(1),
	fifthSimUpgradeBought: false,

	sixthSimUpgradeBought: false,

	seventhSimUpgrade: new Decimal(1),
	seventhSimUpgradeBought: false,

	eighthSimUpgradeBought: false,

	hasUnlockedSim: false,
	hasUnlockedSimUps: false,

	hasUnlockedElectrons: false,
	electronCurrent: new Decimal(0),
	electronInterval: new Decimal(1000),
	electrons: new Decimal(1),
	electronEffect: new Decimal(1),
	maxElectrons: new Decimal(1e10),
	electronGain: new Decimal(1.01),
	electronGainBought: new Decimal(0),
	electronGain3x4y: new Decimal(0),
	electronGain4x4y: new Decimal(0),
	electronGainGain: new Decimal(1),
	electronGainFinal: new Decimal(1.01),
	electronGainFromOmegaUpgrade3x3y: new Decimal(1),
	atoms: new Decimal(0),
	totalAtomResets: new Decimal(0),

	firstElectronUpgradeCost: new Decimal(1e5),
	firstElectronUpgradeFix: false,
	firstElectronUpgradeBought: new Decimal(0),
	secondElectronUpgradeCost: new Decimal(1e5),
	thirdElectronUpgradeCost: new Decimal(1000),
	thirdElectronUpgradeCost4x3y: new Decimal(1),
	thirdElectronUpgradeCost4x4y: new Decimal(1),

	firstAtomUpgradeBought: new Decimal(0),
	secondAtomUpgradeBought: new Decimal(0),
	thirdAtomUpgradeBought: new Decimal(0),

	firstAtomUpgrade3: new Decimal(1),
	secondAtomUpgrade3: new Decimal(1),
	thirdAtomUpgrade3: new Decimal(0),

	firstAtomUpgradeCost: new Decimal(1),
	secondAtomUpgradeCost: new Decimal(1),
	thirdAtomUpgradeCost: new Decimal(1),

	hasUnlockedReality: false,
	realities: new Decimal(0),
	realityPoints: new Decimal(0),
	realityEnergy: new Decimal(0),

	maxRealityBonus: new Decimal(1),
	checkedRealityBonus: new Decimal(0),
	realityBonus1: new Decimal(1),
	realityBonus2: new Decimal(1),
	realityBonus3: new Decimal(1),
	realityBonus4: new Decimal(1),
	realityBonus5: new Decimal(1),
	realityBonus6: new Decimal(1),
	realityBonus7: new Decimal(1),
	realityBonus1Checked: false,
	realityBonus2Checked: false,
	realityBonus3Checked: false,
	realityBonus4Checked: false,
	realityBonus5Checked: false,
	realityBonus6Checked: false,
	realityBonus7Checked: false,

	firstRealityGeneratorCost: new Decimal(1),
	secondRealityGeneratorCost: new Decimal(100),
	thirdRealityGeneratorCost: new Decimal(1e4),
	fourthRealityGeneratorCost: new Decimal(1e6),
	fifthRealityGeneratorCost: new Decimal(1e8),
	sixthRealityGeneratorCost: new Decimal(1e10),
	seventhRealityGeneratorCost: new Decimal(1e12),
	eighthRealityGeneratorCost: new Decimal(1e14),

	firstRealityGeneratorCostInc: new Decimal(1.5),
	secondRealityGeneratorCostInc: new Decimal(1.5),
	thirdRealityGeneratorCostInc: new Decimal(1.5),
	fourthRealityGeneratorCostInc: new Decimal(1.5),
	fifthRealityGeneratorCostInc: new Decimal(1.5),
	sixthRealityGeneratorCostInc: new Decimal(1.5),
	seventhRealityGeneratorCostInc: new Decimal(1.5),
	eighthRealityGeneratorCostInc: new Decimal(1.5),

	firstRealityGeneratorCostIncInc: new Decimal(1.1),
	secondRealityGeneratorCostIncInc: new Decimal(1.1),
	thirdRealityGeneratorCostIncInc: new Decimal(1.1),
	fourthRealityGeneratorCostIncInc: new Decimal(1.1),
	fifthRealityGeneratorCostIncInc: new Decimal(1.1),
	sixthRealityGeneratorCostIncInc: new Decimal(1.1),
	seventhRealityGeneratorCostIncInc: new Decimal(1.1),
	eighthRealityGeneratorCostIncInc: new Decimal(1.1),

	firstRealityGeneratorAmount: new Decimal(0),
	secondRealityGeneratorAmount: new Decimal(0),
	thirdRealityGeneratorAmount: new Decimal(0),
	fourthRealityGeneratorAmount: new Decimal(0),
	fifthRealityGeneratorAmount: new Decimal(0),
	sixthRealityGeneratorAmount: new Decimal(0),
	seventhRealityGeneratorAmount: new Decimal(0),
	eighthRealityGeneratorAmount: new Decimal(0),

	firstRealityGeneratorBought: new Decimal(0),
	secondRealityGeneratorBought: new Decimal(0),
	thirdRealityGeneratorBought: new Decimal(0),
	fourthRealityGeneratorBought: new Decimal(0),
	fifthRealityGeneratorBought: new Decimal(0),
	sixthRealityGeneratorBought: new Decimal(0),
	seventhRealityGeneratorBought: new Decimal(0),
	eighthRealityGeneratorBought: new Decimal(0),

	firstRealityGeneratorMult: new Decimal(1),
	secondRealityGeneratorMult: new Decimal(1),
	thirdRealityGeneratorMult: new Decimal(1),
	fourthRealityGeneratorMult: new Decimal(1),
	fifthRealityGeneratorMult: new Decimal(1),
	sixthRealityGeneratorMult: new Decimal(1),
	seventhRealityGeneratorMult: new Decimal(1),
	eighthRealityGeneratorMult: new Decimal(1),

	firstRealityGeneratorFinalMult: new Decimal(1),
	secondRealityGeneratorFinalMult: new Decimal(1),
	thirdRealityGeneratorFinalMult: new Decimal(1),
	fourthRealityGeneratorFinalMult: new Decimal(1),
	fifthRealityGeneratorFinalMult: new Decimal(1),

	sixthRealityGeneratorFinalMult: new Decimal(1),
	seventhRealityGeneratorFinalMult: new Decimal(1),
	eighthRealityGeneratorFinalMult: new Decimal(1),

	hasUnlockedBattleTower: false,

	friendlyLevel: new Decimal(1),
	highestFriendlyLevel: new Decimal(1),
	skillpoints: new Decimal(0),
	friendlyStamina: new Decimal(3),
	friendlyHealthTotal: new Decimal(50),
	friendlyHealthCurrent: new Decimal(50),
	friendlyStrength: new Decimal(3),
	friendlyArmor: new Decimal(1),
	friendlyRegeneration: new Decimal(1),
	friendlyAgility: new Decimal(1),

	enemyLevel: new Decimal(1),
	highestEnemyLevel: new Decimal(1),
	enemyStamina: new Decimal(5),
	enemyHealthTotal: new Decimal(50),
	enemyHealthCurrent: new Decimal(50),
	enemyStrength: new Decimal(1),
	enemyArmor: new Decimal(1),
	enemyRegeneration: new Decimal(1),
	enemyAgility: new Decimal(1),

	currentXp: new Decimal(0),
	needToLvlUpXp: new Decimal(50),

	maxEnemyLevel: new Decimal(100),
	bossesKilled: new Decimal(0),

	isLegendary: false,
	isBoss: false,

	isResting: true,

	hasUnlockedTalents: false,
	talent1Effect: new Decimal(0),
	talent1IsActive: false,
	talent2Effect: new Decimal(0),
	talent2IsActive: false,
	talent3Effect: new Decimal(0),
	talent3IsActive: false,
	talent4Effect: new Decimal(0),
	talent4IsActive: false,
	talent5Effect: new Decimal(0),
	talent5IsActive: false,
	talent6Effect: new Decimal(0),
	talent6IsActive: false,
	talent7Effect: new Decimal(0),
	talent7IsActive: false,
	talent8Effect: new Decimal(0),
	talent8IsActive: false,
	talent9Effect: new Decimal(0),
	talent9IsActive: false,
	talent10Effect: new Decimal(0),
	talent10IsActive: false,
	talent11Effect: new Decimal(0),
	talent11IsActive: false,
	talent12Effect: new Decimal(0),
	talent12IsActive: false,
	talent13Effect: new Decimal(0),
	talent13IsActive: false,
	talent14Effect: new Decimal(0),
	talent14IsActive: false,
	talent15Effect: new Decimal(0),
	talent15Effect2: new Decimal(0),
	talent15IsActive: false,

	hasUnlockedAtomShop: false,
	atomShopItem1Bought: false,
	atomShopItem2Bought: false,
	atomShopItem3Bought: false,
	atomShopItem4Bought: false,
	atomShopItem5Bought: false,
	atomShopItem6Bought: false,
	atomShopItem7Bought: false,
	atomShopItem8Bought: false,
	atomShopItem9Bought: false,
	atomShopItem10Bought: false,
	atomShopItem11Bought: false,
	atomShopItem12Bought: false,
	atomShopItem13Bought: false,
	atomShopItem14Bought: false,
	atomShopItem15Bought: false,
	atomShopItem16Bought: false,
	atomShopItem17Bought: false,
	atomShopItem18Bought: false,
	atomShopItem19Bought: false,
	atomShopItem20Bought: false,

	atomShopItemsBought: new Decimal(0),

	atomShopItem1Counter: new Decimal(0),
	atomShopItem1Skillpoints: new Decimal(0),

	atomShopItem9Counter: new Decimal(0),
	atomShopItem9Skillpoints: new Decimal(0),

	atomShopItem2Effect: new Decimal(1),

	atomShopItem11Effect: new Decimal(1),

	atomShopItem13Effect: new Decimal(1000),

	atomShopItem16Effect: new Decimal(1),

	atomShopItem18Effect: new Decimal(1),

	atomShopItem19Effect: new Decimal(1),

	hasUnlockedTraining: false,
	superSkillpoints: new Decimal(0),
	superStamina: new Decimal(0),
	superStrength: new Decimal(0),
	superArmor: new Decimal(0),
	superRegeneration: new Decimal(0),
	superAgility: new Decimal(0),

	build1Exists: false,
	build1TotalSkillpoints: new Decimal(0),
	build1TotalSuperSkillpoints: new Decimal(0),
	build1Stamina: new Decimal(0),
	build1Strength: new Decimal(0),
	build1Armor: new Decimal(0),
	build1Regeneration: new Decimal(0),
	build1Agility: new Decimal(0),
	build1SuperStamina: new Decimal(0),
	build1SuperStrength: new Decimal(0),
	build1SuperArmor: new Decimal(0),
	build1SuperRegeneration: new Decimal(0),
	build1SuperAgility: new Decimal(0),
	build1TalentRow1: 0,
	build1TalentRow2: 0,
	build1TalentRow3: 0,
	build1TalentRow4: 0,
	build1TalentRow5: 0,

	build2Exists: false,
	build2TotalSkillpoints: new Decimal(0),
	build2TotalSuperSkillpoints: new Decimal(0),
	build2Stamina: new Decimal(0),
	build2Strength: new Decimal(0),
	build2Armor: new Decimal(0),
	build2Regeneration: new Decimal(0),
	build2Agility: new Decimal(0),
	build2SuperStamina: new Decimal(0),
	build2SuperStrength: new Decimal(0),
	build2SuperArmor: new Decimal(0),
	build2SuperRegeneration: new Decimal(0),
	build2SuperAgility: new Decimal(0),
	build2TalentRow1: 0,
	build2TalentRow2: 0,
	build2TalentRow3: 0,
	build2TalentRow4: 0,
	build2TalentRow5: 0,

	build3Exists: false,
	build3TotalSkillpoints: new Decimal(0),
	build3TotalSuperSkillpoints: new Decimal(0),
	build3Stamina: new Decimal(0),
	build3Strength: new Decimal(0),
	build3Armor: new Decimal(0),
	build3Regeneration: new Decimal(0),
	build3Agility: new Decimal(0),
	build3SuperStamina: new Decimal(0),
	build3SuperStrength: new Decimal(0),
	build3SuperArmor: new Decimal(0),
	build3SuperRegeneration: new Decimal(0),
	build3SuperAgility: new Decimal(0),
	build3TalentRow1: 0,
	build3TalentRow2: 0,
	build3TalentRow3: 0,
	build3TalentRow4: 0,
	build3TalentRow5: 0,

	build4Exists: false,
	build4TotalSkillpoints: new Decimal(0),
	build4TotalSuperSkillpoints: new Decimal(0),
	build4Stamina: new Decimal(0),
	build4Strength: new Decimal(0),
	build4Armor: new Decimal(0),
	build4Regeneration: new Decimal(0),
	build4Agility: new Decimal(0),
	build4SuperStamina: new Decimal(0),
	build4SuperStrength: new Decimal(0),
	build4SuperArmor: new Decimal(0),
	build4SuperRegeneration: new Decimal(0),
	build4SuperAgility: new Decimal(0),
	build4TalentRow1: 0,
	build4TalentRow2: 0,
	build4TalentRow3: 0,
	build4TalentRow4: 0,
	build4TalentRow5: 0,

	lastNormalPanel: 0,
	lastExpansionPanel: 0,
	lastOmegaPanel: 0,
	lastRealityPanel: 0,
	lastAutobuyerPanel: 0,
	lastExtraPanel: 0,
	hasSwitchedToExpansionGenerators: false,
	hasSwitchedToABG: false,
	hasSwitchedToOmegaGenerators: false,
	hasSwitchedToSim: false,
	hasSwitchedToSimUpgrades: false,
	hasSwitchedToElectrons: false,
	hasSwitchedToRealityGenerators: false,
	hasSwitchedToBattleTower: false,
	hasSwitchedToTalents: false,
	hasSwitchedToAtomShop: false,
	hasSwitchedToAutobuyer: false,
	hasSwitchedToFillBar: false,

	hasUnlockedFillBar: false,
	hasSwitchedToFillBar: false,

	fillBarFinalMult: new Decimal(1),
	fillBarGold: new Decimal(1),

	firstFillBarLevel: new Decimal(0),
	firstFillBarCost: new Decimal(1),
	firstFillBarCostfinal: new Decimal(1),
	firstFillBarSpeed: new Decimal(3000),
	firstFillBarSpeedFinal: new Decimal(3000),
	firstFillBarSpeedBase: new Decimal(3000),
	firstFillBarProgress: new Decimal(0),
	firstFillBarAscension: new Decimal(0),
	firstFillBarMult: new Decimal(1),
	firstFillBarMultPerFill: new Decimal(0.01),
	firstFillBarMultPerFillFinal: new Decimal(0.01),
	firstFillBarBought: new Decimal(0),

	secondFillBarLevel: new Decimal(0),
	secondFillBarCost: new Decimal(50),
	secondFillBarCostFinal: new Decimal(50),
	secondFillBarSpeed: new Decimal(5000),
	secondFillBarSpeedFinal: new Decimal(5000),
	secondFillBarSpeedBase: new Decimal(5000),
	secondFillBarProgress: new Decimal(0),
	secondFillBarAscension: new Decimal(0),
	secondFillBarMult: new Decimal(1),
	secondFillBarMultPerFill: new Decimal(0.01),
	secondFillBarMultPerFillFinal: new Decimal(0.01),
	secondFillBarBought: new Decimal(0),

	thirdFillBarLevel: new Decimal(0),
	thirdFillBarCost: new Decimal(1000),
	thirdFillBarCostFinal: new Decimal(1000),
	thirdFillBarSpeed: new Decimal(10000),
	thirdFillBarSpeedFinal: new Decimal(10000),
	thirdFillBarSpeedBase: new Decimal(10000),
	thirdFillBarProgress: new Decimal(0),
	thirdFillBarAscension: new Decimal(0),
	thirdFillBarMult: new Decimal(1),
	thirdFillBarMultPerFill: new Decimal(0.01),
	thirdFillBarMultPerFillFinal: new Decimal(0.01),
	thirdFillBarBought: new Decimal(0),

	fourthFillBarLevel: new Decimal(0),
	fourthFillBarCost: new Decimal(1e5),
	fourthFillBarCostFinal: new Decimal(1e5),
	fourthFillBarSpeed: new Decimal(15000),
	fourthFillBarSpeedFinal: new Decimal(15000),
	fourthFillBarSpeedBase: new Decimal(15000),
	fourthFillBarProgress: new Decimal(0),
	fourthFillBarAscension: new Decimal(0),
	fourthFillBarMult: new Decimal(1),
	fourthFillBarMultPerFill: new Decimal(0.01),
	fourthFillBarMultPerFillFinal: new Decimal(0.01),
	fourthFillBarBought: new Decimal(0),

	fifthFillBarLevel: new Decimal(0),
	fifthFillBarCost: new Decimal(1e8),
	fifthFillBarCostFinal: new Decimal(1e8),
	fifthFillBarSpeed: new Decimal(20000),
	fifthFillBarSpeedFinal: new Decimal(20000),
	fifthFillBarSpeedBase: new Decimal(20000),
	fifthFillBarProgress: new Decimal(0),
	fifthFillBarAscension: new Decimal(0),
	fifthFillBarMult: new Decimal(1),
	fifthFillBarMultPerFill: new Decimal(0.01),
	fifthFillBarMultPerFillFinal: new Decimal(0.01),
	fifthFillBarBought: new Decimal(0),

	sixthFillBarLevel: new Decimal(0),
	sixthFillBarCost: new Decimal(1e12),
	sixthFillBarCostFinal: new Decimal(1e12),
	sixthFillBarSpeed: new Decimal(25000),
	sixthFillBarSpeedFinal: new Decimal(25000),
	sixthFillBarSpeedBase: new Decimal(25000),
	sixthFillBarProgress: new Decimal(0),
	sixthFillBarAscension: new Decimal(0),
	sixthFillBarMult: new Decimal(1),
	sixthFillBarMultPerFill: new Decimal(0.01),
	sixthFillBarMultPerFillFinal: new Decimal(0.01),
	sixthFillBarBought: new Decimal(0),

	seventhFillBarLevel: new Decimal(0),
	seventhFillBarCost: new Decimal(1e16),
	seventhFillBarCostFinal: new Decimal(1e16),
	seventhFillBarSpeed: new Decimal(30000),
	seventhFillBarSpeedFinal: new Decimal(30000),
	seventhFillBarSpeedBase: new Decimal(30000),
	seventhFillBarProgress: new Decimal(0),
	seventhFillBarAscension: new Decimal(0),
	seventhFillBarMult: new Decimal(1),
	seventhFillBarMultPerFill: new Decimal(0.01),
	seventhFillBarMultPerFillFinal: new Decimal(0.01),
	seventhFillBarBought: new Decimal(0),

	eighthFillBarLevel: new Decimal(0),
	eighthFillBarCost: new Decimal(1e25),
	eighthFillBarCostFinal: new Decimal(1e25),
	eighthFillBarSpeed: new Decimal(60000),
	eighthFillBarSpeedFinal: new Decimal(60000),
	eighthFillBarSpeedBase: new Decimal(60000),
	eighthFillBarProgress: new Decimal(0),
	eighthFillBarAscension: new Decimal(0),
	eighthFillBarMult: new Decimal(1),
	eighthFillBarMultPerFill: new Decimal(0.01),
	eighthFillBarMultPerFillFinal: new Decimal(0.01),
	eighthFillBarBought: new Decimal(0),

	recreateMult: new Decimal(1),

	transcensionPoints: new Decimal(0),

	hasUnlockedTranscensionUpgrades: false,
	hasSwitchedToTranscensionUpgrades: false,

	transcensionUpgrade1: new Decimal(1),
	transcensionUpgrade1Cost: new Decimal(1),
	transcensionUpgrade1Bought: new Decimal(0),
	transcensionUpgrade2: new Decimal(1),
	transcensionUpgrade2Cost: new Decimal(1),
	transcensionUpgrade2Bought: new Decimal(0),
	transcensionUpgrade3: new Decimal(1),
	transcensionUpgrade3Cost: new Decimal(1),
	transcensionUpgrade3Bought: new Decimal(0),
	transcensionUpgrade4: new Decimal(1),
	transcensionUpgrade4Cost: new Decimal(1),
	transcensionUpgrade4Bought: new Decimal(0),
	transcensionUpgrade5: new Decimal(1),
	transcensionUpgrade5Cost: new Decimal(1),
	transcensionUpgrade5Bought: new Decimal(0),
	transcensionUpgrade6: new Decimal(1),
	transcensionUpgrade6Cost: new Decimal(1),
	transcensionUpgrade6Bought: new Decimal(0),
	transcensionUpgrade7: new Decimal(1),
	transcensionUpgrade7Cost: new Decimal(1),
	transcensionUpgrade7Bought: new Decimal(0),
	transcensionUpgrade8: new Decimal(1),
	transcensionUpgrade8Cost: new Decimal(1),
	transcensionUpgrade8Bought: new Decimal(0),

	milestone1: false,
	milestone2: false,
	milestone3: false,
	milestone4: false,
	milestone5: false,
	milestone6: false,
	milestone7: false,
	milestone8: false,
	milestone9: false,
	milestone10: false,
	milestone11: false,
	milestone12: false,
	milestone13: false,
	milestone14: false,
	milestone15: false,
	milestone16: false,
	milestone17: false,
	milestone18: false,
	milestone19: false,
	milestone20: false,
	milestone21: false,
	milestone22: false,
	milestone23: false,
	milestone24: false,
	milestone24Mult: new Decimal(1),

	maxParticleAssimilatorAutobuy: 0,

	hyperPoints: new Decimal(0),

	hasUnlockedHypercensionUpgrades: false,
	hasSwitchedToHypercensionUpgrades: false,

	hypercensionUpgrade1: new Decimal(1),
	hypercensionUpgrade1Cost: new Decimal(1),
	hypercensionUpgrade2: new Decimal(1),
	hypercensionUpgrade2Cost: new Decimal(1),
	hypercensionUpgrade3: new Decimal(1),
	hypercensionUpgrade3Cost: new Decimal(1),
	hypercensionUpgrade4: new Decimal(1),
	hypercensionUpgrade4Cost: new Decimal(1),
	hypercensionUpgrade5: new Decimal(1),
	hypercensionUpgrade5Cost: new Decimal(10),
	hypercensionUpgrade5Bought: false,
	hypercensionUpgrade6: new Decimal(1),
	hypercensionUpgrade6Cost: new Decimal(1000),
	hypercensionUpgrade6Bought: false,
	hypercensionUpgrade7: new Decimal(1),
	hypercensionUpgrade7Cost: new Decimal(1e4),
	hypercensionUpgrade7Bought: false,
	hypercensionUpgrade8: new Decimal(1),
	hypercensionUpgrade8Cost: new Decimal(1e5),
	hypercensionUpgrade8Bought: false
};
function hardReset() {
	player = { ...defaultPlayer };

}

export default {
  player,
  hardReset
}
